name: Deploy to Firebase Dev Hosting

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENGAGEMENTINVITATION_1D16A }}
          projectId: engagementinvitation-1d16a
          channelId: live
          target: engagement-invitation-dev
